FROM  alpine:latest

USER root

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
RUN apk --update --no-cache add xvfb hunspell dbus firefox
#CMD ["/usr/bin/firefox", "-no-remote"]
CMD ["Xvfb :10"]
CMD ["firefox"]
